### PR TITLE
Fix `dependsOn` bug with `show` and `hide` field methods

### PR DESCRIPTION
**Pull request by LorenzoAlu**
Fix issue [255](https://github.com/outl1ne/nova-multiselect-field/issues/225)

I have fixed the bug that occurred with the simulated use of the `dependsOn` methods with `hide` and `show` :)

On this occasion added a default value for the `tagPlaceholder` tag for the Vue `MultiSelect` package, as that message was untranslatable into other languages. :) This can be remedied by using the native `help` method of laraval nova.

What do you think? Will this modification work?

### CODE REVIEW

**Comment by Tarpsvo** [comment]
Heya! Thanks a ton for the PR. :) It's now released in 4.4.0.

**Comment by Tarpsvo** [comment]
Heya! Had to revert this as it broke the behaviour of other fields. I had forgotten that FormData does not allow of serialization of null's. It will send them as the string "null" which causes them to be saved to the database. Empty string is the only way to send null-values to the back-end.

I'm not sure what causes the show() and hide() to misbehave though yet.

**Comment by LorenzoAlu** [comment]
@Tarpsvo ok i'll try to solve it in differente way ;)

**Comment by LorenzoAlu** [comment]
@Tarpsvo here we are https://github.com/outl1ne/nova-multiselect-field/pull/232 ;)

**Pull request merged**
